manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware@964c54139dcc5fca466eb2a6dc72b4092c7152a0
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
